version: "3.9"
name: python3-template
services:
  python3-template:
    image: python3-template
    container_name: python3-template
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - USE_CUDA=${USE_CUDA:-false}
        - USE_ROOT=${USE_ROOT:-false}
        - USER_ID=${USER_ID:-1000}
        - GROUP_ID=${GROUP_ID:-1000}
    volumes:
      - type: bind
        source: ..
        target: /projects
      - type: bind
        source: ~/.ssh
        target: /home/user/.ssh
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
