version: "3.9"
name: python-template
services:
  python-template:
    image: python-template
    container_name: python-template
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - USER_NAME=${USER_NAME:?}
        - USER_ID=${USER_ID:?}
        - GROUP_ID=${GROUP_ID:?}
        - HOME_DIRECTORY=${HOME_DIRECTORY:?}
        - PYTHON_VERSION=${PYTHON_VERSION:?}
      ssh:
        - default
    volumes:
      - type: bind
        source: ~/.ssh
        target: ${HOME_DIRECTORY:?}/.ssh
