version: "3.9"
name: python3-template
services:
  python3-template:
    image: python3-template
    container_name: python3-template
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - ROOT=${ROOT:-0}
        - USER_ID=${USER_ID:-1000}
        - GROUP_ID=${GROUP_ID:-1000}
        - USER_NAME=${USER_NAME:-user}
        - GROUP_NAME=${GROUP_NAME:-user}
        - HOME_DIR=${HOME_DIR:-/home/user}
        - SHELL=${SHELL:-/bin/bash}
        - VENV_DIR=${VENV_DIR:-/home/user/.virtualenvs/venv}
    volumes:
      - type: bind
        source: ..
        target: /projects
